name: Main CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:

  build_frontend:
    name: Build Front End
    runs-on: ubuntu-latest
    steps:

    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        npm ci

    - name: Build Front End Files
      run: |
        npm run build
